### ISSUE TITLE
Pt-Layout

### ISSUE THREAD

**Issue by mcpeixoto** [donid/akuhell#3]
heya I'm a newbie too! 
I just want to make a duckino that works with portuguese layout and it's hard to implement non-US layouts since I never saw a tutorial on that, can you help me with that?

**Comment by donid** [comment]
I would recommend to fork this project, and try to compile keyboard_layouts.ino as it is and upload it to your device. Your device should then start to type a bunch of characters every second - obviously some will not match the characters specified in the source code, because the layout is set to German. If this works, you can continue and add a define for portuguese in akuhell_languages.h and use it in keyboard_layouts.ino.
Finally, you have to modify/extend the code of Keyboard_convertUtf8CharacterToKeycode in akuhell.h.

When you have successfully implemented and tested the new layout and you are willing to share it, you are welcome to open a pull request.

**Comment by donid** [comment]
P.S.: I am not familiar with "duckino", but keep in mind: This project is code that has to be compiled with the Arduino IDE and the result is a binary firmware that must be flashed into a compatible device.
